/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kafkaleaderboard.app;

import kafkaleaderboard.list.LinkedList;

import static kafkaleaderboard.utilities.StringUtils.join;
import static kafkaleaderboard.utilities.StringUtils.split;

import java.util.Properties;

import static kafkaleaderboard.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;
import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.streams.StreamsConfig;
import org.apache.kafka.streams.Topology;
import org.apache.kafka.streams.state.HostInfo;

public class App {
    public static void main(String[] args) {
        Topology topology = LeaderBoardTopology.build();

        String host = System.getProperty("host");
        Integer port = Integer.parseInt(System.getProperty("port"));
        String stateDir = System.getProperty("stateDir");
        String endpoint = String.format("%s:%s", "localhost", "7000");

        Properties props = new Properties();
        props.put(StreamsConfig.APPLICATION_ID_CONFIG, "dev");
        props.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:29092");
        props.put(StreamsConfig.CACHE_MAX_BYTES_BUFFERING_CONFIG, 0);
        props.put(StreamsConfig.APPLICATION_SERVER_CONFIG, endpoint);
        props.put(StreamsConfig.STATE_DIR_CONFIG, "/tmp/kafka-streams");

        KafkaStreams streams = new KafkaStreams(topology, props);

        Runtime.getRuntime().addShutdownHook(new Thread(streams::close));
        // start streaming!
        streams.start();

        HostInfo hostInfo = new HostInfo(host, port);
        LeaderboardService service = new LeaderboardService(hostInfo, streams);
        service.start();
    }
}
